// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contracts

import "encoding/json"
import "fmt"
import "reflect"
import "time"

type ApprovalRequestedSchemaJson struct {
	// ApprovalId corresponds to the JSON schema field "approvalId".
	ApprovalId string `json:"approvalId" yaml:"approvalId" mapstructure:"approvalId"`

	// What is being requested (resource, scope, preview).
	Context ApprovalRequestedSchemaJsonContext `json:"context,omitempty" yaml:"context,omitempty" mapstructure:"context,omitempty"`

	// Kind corresponds to the JSON schema field "kind".
	Kind ApprovalRequestedSchemaJsonKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Risk corresponds to the JSON schema field "risk".
	Risk ApprovalRequestedSchemaJsonRisk `json:"risk" yaml:"risk" mapstructure:"risk"`

	// TaskId corresponds to the JSON schema field "taskId".
	TaskId string `json:"taskId" yaml:"taskId" mapstructure:"taskId"`
}

// What is being requested (resource, scope, preview).
type ApprovalRequestedSchemaJsonContext map[string]interface{}

type ApprovalRequestedSchemaJsonKind string

const ApprovalRequestedSchemaJsonKindDataExport ApprovalRequestedSchemaJsonKind = "data_export"
const ApprovalRequestedSchemaJsonKindFsWrite ApprovalRequestedSchemaJsonKind = "fs_write"
const ApprovalRequestedSchemaJsonKindNet ApprovalRequestedSchemaJsonKind = "net"
const ApprovalRequestedSchemaJsonKindShell ApprovalRequestedSchemaJsonKind = "shell"
const ApprovalRequestedSchemaJsonKindTool ApprovalRequestedSchemaJsonKind = "tool"

var enumValues_ApprovalRequestedSchemaJsonKind = []interface{}{
	"tool",
	"data_export",
	"shell",
	"fs_write",
	"net",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ApprovalRequestedSchemaJsonKind) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ApprovalRequestedSchemaJsonKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ApprovalRequestedSchemaJsonKind, v)
	}
	*j = ApprovalRequestedSchemaJsonKind(v)
	return nil
}

type ApprovalRequestedSchemaJsonRisk string

const ApprovalRequestedSchemaJsonRiskHigh ApprovalRequestedSchemaJsonRisk = "high"
const ApprovalRequestedSchemaJsonRiskLow ApprovalRequestedSchemaJsonRisk = "low"
const ApprovalRequestedSchemaJsonRiskMedium ApprovalRequestedSchemaJsonRisk = "medium"

var enumValues_ApprovalRequestedSchemaJsonRisk = []interface{}{
	"low",
	"medium",
	"high",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ApprovalRequestedSchemaJsonRisk) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ApprovalRequestedSchemaJsonRisk {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ApprovalRequestedSchemaJsonRisk, v)
	}
	*j = ApprovalRequestedSchemaJsonRisk(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ApprovalRequestedSchemaJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["approvalId"]; raw != nil && !ok {
		return fmt.Errorf("field approvalId in ApprovalRequestedSchemaJson: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in ApprovalRequestedSchemaJson: required")
	}
	if _, ok := raw["risk"]; raw != nil && !ok {
		return fmt.Errorf("field risk in ApprovalRequestedSchemaJson: required")
	}
	if _, ok := raw["taskId"]; raw != nil && !ok {
		return fmt.Errorf("field taskId in ApprovalRequestedSchemaJson: required")
	}
	type Plain ApprovalRequestedSchemaJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ApprovalRequestedSchemaJson(plain)
	return nil
}

type ApprovalResolvedSchemaJson struct {
	// ApprovalId corresponds to the JSON schema field "approvalId".
	ApprovalId string `json:"approvalId" yaml:"approvalId" mapstructure:"approvalId"`

	// Decision corresponds to the JSON schema field "decision".
	Decision ApprovalResolvedSchemaJsonDecision `json:"decision" yaml:"decision" mapstructure:"decision"`

	// Reason corresponds to the JSON schema field "reason".
	Reason *string `json:"reason,omitempty" yaml:"reason,omitempty" mapstructure:"reason,omitempty"`

	// Human actor id (P7: human in the loop).
	ResolvedBy string `json:"resolvedBy" yaml:"resolvedBy" mapstructure:"resolvedBy"`

	// TaskId corresponds to the JSON schema field "taskId".
	TaskId string `json:"taskId" yaml:"taskId" mapstructure:"taskId"`
}

type ApprovalResolvedSchemaJsonDecision string

const ApprovalResolvedSchemaJsonDecisionApprove ApprovalResolvedSchemaJsonDecision = "approve"
const ApprovalResolvedSchemaJsonDecisionReject ApprovalResolvedSchemaJsonDecision = "reject"

var enumValues_ApprovalResolvedSchemaJsonDecision = []interface{}{
	"approve",
	"reject",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ApprovalResolvedSchemaJsonDecision) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ApprovalResolvedSchemaJsonDecision {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ApprovalResolvedSchemaJsonDecision, v)
	}
	*j = ApprovalResolvedSchemaJsonDecision(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ApprovalResolvedSchemaJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["approvalId"]; raw != nil && !ok {
		return fmt.Errorf("field approvalId in ApprovalResolvedSchemaJson: required")
	}
	if _, ok := raw["decision"]; raw != nil && !ok {
		return fmt.Errorf("field decision in ApprovalResolvedSchemaJson: required")
	}
	if _, ok := raw["resolvedBy"]; raw != nil && !ok {
		return fmt.Errorf("field resolvedBy in ApprovalResolvedSchemaJson: required")
	}
	if _, ok := raw["taskId"]; raw != nil && !ok {
		return fmt.Errorf("field taskId in ApprovalResolvedSchemaJson: required")
	}
	type Plain ApprovalResolvedSchemaJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ApprovalResolvedSchemaJson(plain)
	return nil
}

type ArtifactCreatedSchemaJson struct {
	// ArtifactId corresponds to the JSON schema field "artifactId".
	ArtifactId string `json:"artifactId" yaml:"artifactId" mapstructure:"artifactId"`

	// Mime corresponds to the JSON schema field "mime".
	Mime string `json:"mime" yaml:"mime" mapstructure:"mime"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path" yaml:"path" mapstructure:"path"`

	// Sha256 corresponds to the JSON schema field "sha256".
	Sha256 string `json:"sha256" yaml:"sha256" mapstructure:"sha256"`

	// Size corresponds to the JSON schema field "size".
	Size int `json:"size" yaml:"size" mapstructure:"size"`

	// TaskId corresponds to the JSON schema field "taskId".
	TaskId string `json:"taskId" yaml:"taskId" mapstructure:"taskId"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ArtifactCreatedSchemaJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["artifactId"]; raw != nil && !ok {
		return fmt.Errorf("field artifactId in ArtifactCreatedSchemaJson: required")
	}
	if _, ok := raw["mime"]; raw != nil && !ok {
		return fmt.Errorf("field mime in ArtifactCreatedSchemaJson: required")
	}
	if _, ok := raw["path"]; raw != nil && !ok {
		return fmt.Errorf("field path in ArtifactCreatedSchemaJson: required")
	}
	if _, ok := raw["sha256"]; raw != nil && !ok {
		return fmt.Errorf("field sha256 in ArtifactCreatedSchemaJson: required")
	}
	if _, ok := raw["size"]; raw != nil && !ok {
		return fmt.Errorf("field size in ArtifactCreatedSchemaJson: required")
	}
	if _, ok := raw["taskId"]; raw != nil && !ok {
		return fmt.Errorf("field taskId in ArtifactCreatedSchemaJson: required")
	}
	type Plain ArtifactCreatedSchemaJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ArtifactCreatedSchemaJson(plain)
	return nil
}

// Capability token claims. Issued by the kernel CapabilityIssuer at minimal scope;
// verified at tool-execution time. The token carrier is a server-signed envelope;
// revocation is enforced by checking tokenId/version at use-time (see spec 11.1).
type CapabilitySchemaJson struct {
	// Constraints corresponds to the JSON schema field "constraints".
	Constraints *CapabilitySchemaJsonConstraints `json:"constraints,omitempty" yaml:"constraints,omitempty" mapstructure:"constraints,omitempty"`

	// Resource class. tool:<name> is a parameterized form.
	Resource string `json:"resource" yaml:"resource" mapstructure:"resource"`

	// false means a hard-deny capability that can never be minted (uncoverable set).
	Revocable bool `json:"revocable" yaml:"revocable" mapstructure:"revocable"`

	// Scope corresponds to the JSON schema field "scope".
	Scope CapabilitySchemaJsonScope `json:"scope" yaml:"scope" mapstructure:"scope"`

	// TaskId or AgentId this capability is bound to.
	Subject string `json:"subject" yaml:"subject" mapstructure:"subject"`

	// Unique id; checked against the revocation store on every use.
	TokenId string `json:"tokenId" yaml:"tokenId" mapstructure:"tokenId"`

	// Monotonic; bumped on re-issue, validated at use-time.
	Version int `json:"version" yaml:"version" mapstructure:"version"`
}

type CapabilitySchemaJsonConstraints struct {
	// ExpiresAt corresponds to the JSON schema field "expiresAt".
	ExpiresAt *time.Time `json:"expiresAt,omitempty" yaml:"expiresAt,omitempty" mapstructure:"expiresAt,omitempty"`

	// MaxCalls corresponds to the JSON schema field "maxCalls".
	MaxCalls *int `json:"maxCalls,omitempty" yaml:"maxCalls,omitempty" mapstructure:"maxCalls,omitempty"`
}

type CapabilitySchemaJsonScope struct {
	// When bound to a specific Local Agent Runner device.
	DeviceId *string `json:"deviceId,omitempty" yaml:"deviceId,omitempty" mapstructure:"deviceId,omitempty"`

	// Host allow-list for net.
	Domains []string `json:"domains,omitempty" yaml:"domains,omitempty" mapstructure:"domains,omitempty"`

	// Glob allow-list for fs.* resources.
	Paths []string `json:"paths,omitempty" yaml:"paths,omitempty" mapstructure:"paths,omitempty"`

	// WorkspaceId corresponds to the JSON schema field "workspaceId".
	WorkspaceId string `json:"workspaceId" yaml:"workspaceId" mapstructure:"workspaceId"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CapabilitySchemaJsonScope) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["workspaceId"]; raw != nil && !ok {
		return fmt.Errorf("field workspaceId in CapabilitySchemaJsonScope: required")
	}
	type Plain CapabilitySchemaJsonScope
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = CapabilitySchemaJsonScope(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CapabilitySchemaJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["resource"]; raw != nil && !ok {
		return fmt.Errorf("field resource in CapabilitySchemaJson: required")
	}
	if _, ok := raw["revocable"]; raw != nil && !ok {
		return fmt.Errorf("field revocable in CapabilitySchemaJson: required")
	}
	if _, ok := raw["scope"]; raw != nil && !ok {
		return fmt.Errorf("field scope in CapabilitySchemaJson: required")
	}
	if _, ok := raw["subject"]; raw != nil && !ok {
		return fmt.Errorf("field subject in CapabilitySchemaJson: required")
	}
	if _, ok := raw["tokenId"]; raw != nil && !ok {
		return fmt.Errorf("field tokenId in CapabilitySchemaJson: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in CapabilitySchemaJson: required")
	}
	type Plain CapabilitySchemaJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = CapabilitySchemaJson(plain)
	return nil
}

// Transport/storage envelope for every committed event. The `payload` is validated
// separately against the schema named by `type`.
type EnvelopeSchemaJson struct {
	// Who caused this event (user/agent/system id).
	Actor string `json:"actor" yaml:"actor" mapstructure:"actor"`

	// CausationId corresponds to the JSON schema field "causationId".
	CausationId *string `json:"causationId,omitempty" yaml:"causationId,omitempty" mapstructure:"causationId,omitempty"`

	// CorrelationId corresponds to the JSON schema field "correlationId".
	CorrelationId *string `json:"correlationId,omitempty" yaml:"correlationId,omitempty" mapstructure:"correlationId,omitempty"`

	// Per-shard monotonic VISIBLE sequence assigned at commit (see spec 8.1).
	// Cross-stream ordering holds only within a shard.
	GlobalSeq int `json:"globalSeq" yaml:"globalSeq" mapstructure:"globalSeq"`

	// OccurredAt corresponds to the JSON schema field "occurredAt".
	OccurredAt time.Time `json:"occurredAt" yaml:"occurredAt" mapstructure:"occurredAt"`

	// Payload corresponds to the JSON schema field "payload".
	Payload EnvelopeSchemaJsonPayload `json:"payload" yaml:"payload" mapstructure:"payload"`

	// SchemaVer corresponds to the JSON schema field "schemaVer".
	SchemaVer int `json:"schemaVer" yaml:"schemaVer" mapstructure:"schemaVer"`

	// Aggregate instance id, e.g. task:<uuid>
	StreamId string `json:"streamId" yaml:"streamId" mapstructure:"streamId"`

	// Per-stream sequence; basis of optimistic concurrency via UNIQUE(stream_id,
	// stream_seq).
	StreamSeq int `json:"streamSeq" yaml:"streamSeq" mapstructure:"streamSeq"`

	// TenantId corresponds to the JSON schema field "tenantId".
	TenantId string `json:"tenantId" yaml:"tenantId" mapstructure:"tenantId"`

	// Event type, must match a catalog entry.
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

type EnvelopeSchemaJsonPayload map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EnvelopeSchemaJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["actor"]; raw != nil && !ok {
		return fmt.Errorf("field actor in EnvelopeSchemaJson: required")
	}
	if _, ok := raw["globalSeq"]; raw != nil && !ok {
		return fmt.Errorf("field globalSeq in EnvelopeSchemaJson: required")
	}
	if _, ok := raw["occurredAt"]; raw != nil && !ok {
		return fmt.Errorf("field occurredAt in EnvelopeSchemaJson: required")
	}
	if _, ok := raw["payload"]; raw != nil && !ok {
		return fmt.Errorf("field payload in EnvelopeSchemaJson: required")
	}
	if _, ok := raw["schemaVer"]; raw != nil && !ok {
		return fmt.Errorf("field schemaVer in EnvelopeSchemaJson: required")
	}
	if _, ok := raw["streamId"]; raw != nil && !ok {
		return fmt.Errorf("field streamId in EnvelopeSchemaJson: required")
	}
	if _, ok := raw["streamSeq"]; raw != nil && !ok {
		return fmt.Errorf("field streamSeq in EnvelopeSchemaJson: required")
	}
	if _, ok := raw["tenantId"]; raw != nil && !ok {
		return fmt.Errorf("field tenantId in EnvelopeSchemaJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in EnvelopeSchemaJson: required")
	}
	type Plain EnvelopeSchemaJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = EnvelopeSchemaJson(plain)
	return nil
}

type PermissionsChangedSchemaJson struct {
	// Permissions corresponds to the JSON schema field "permissions".
	Permissions PermissionsChangedSchemaJsonPermissions `json:"permissions" yaml:"permissions" mapstructure:"permissions"`

	// Monotonic permissions version (capability-first, spec 7.2).
	Version int `json:"version" yaml:"version" mapstructure:"version"`

	// WorkspaceId corresponds to the JSON schema field "workspaceId".
	WorkspaceId string `json:"workspaceId" yaml:"workspaceId" mapstructure:"workspaceId"`
}

type PermissionsChangedSchemaJsonPermissions struct {
	// Domains corresponds to the JSON schema field "domains".
	Domains []string `json:"domains,omitempty" yaml:"domains,omitempty" mapstructure:"domains,omitempty"`

	// Paths corresponds to the JSON schema field "paths".
	Paths []string `json:"paths,omitempty" yaml:"paths,omitempty" mapstructure:"paths,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PermissionsChangedSchemaJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["permissions"]; raw != nil && !ok {
		return fmt.Errorf("field permissions in PermissionsChangedSchemaJson: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in PermissionsChangedSchemaJson: required")
	}
	if _, ok := raw["workspaceId"]; raw != nil && !ok {
		return fmt.Errorf("field workspaceId in PermissionsChangedSchemaJson: required")
	}
	type Plain PermissionsChangedSchemaJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = PermissionsChangedSchemaJson(plain)
	return nil
}

type TaskCancelledSchemaJson struct {
	// CancelledBy corresponds to the JSON schema field "cancelledBy".
	CancelledBy string `json:"cancelledBy" yaml:"cancelledBy" mapstructure:"cancelledBy"`

	// Reason corresponds to the JSON schema field "reason".
	Reason *string `json:"reason,omitempty" yaml:"reason,omitempty" mapstructure:"reason,omitempty"`

	// TaskId corresponds to the JSON schema field "taskId".
	TaskId string `json:"taskId" yaml:"taskId" mapstructure:"taskId"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskCancelledSchemaJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["cancelledBy"]; raw != nil && !ok {
		return fmt.Errorf("field cancelledBy in TaskCancelledSchemaJson: required")
	}
	if _, ok := raw["taskId"]; raw != nil && !ok {
		return fmt.Errorf("field taskId in TaskCancelledSchemaJson: required")
	}
	type Plain TaskCancelledSchemaJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = TaskCancelledSchemaJson(plain)
	return nil
}

type TaskCompletedSchemaJson struct {
	// Metrics corresponds to the JSON schema field "metrics".
	Metrics *TaskCompletedSchemaJsonMetrics `json:"metrics,omitempty" yaml:"metrics,omitempty" mapstructure:"metrics,omitempty"`

	// Final structured result.
	Result TaskCompletedSchemaJsonResult `json:"result,omitempty" yaml:"result,omitempty" mapstructure:"result,omitempty"`

	// TaskId corresponds to the JSON schema field "taskId".
	TaskId string `json:"taskId" yaml:"taskId" mapstructure:"taskId"`
}

type TaskCompletedSchemaJsonMetrics struct {
	// CostUsd corresponds to the JSON schema field "costUsd".
	CostUsd *float64 `json:"costUsd,omitempty" yaml:"costUsd,omitempty" mapstructure:"costUsd,omitempty"`

	// Tokens corresponds to the JSON schema field "tokens".
	Tokens *int `json:"tokens,omitempty" yaml:"tokens,omitempty" mapstructure:"tokens,omitempty"`

	// WallClockMs corresponds to the JSON schema field "wallClockMs".
	WallClockMs *int `json:"wallClockMs,omitempty" yaml:"wallClockMs,omitempty" mapstructure:"wallClockMs,omitempty"`
}

// Final structured result.
type TaskCompletedSchemaJsonResult map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskCompletedSchemaJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["taskId"]; raw != nil && !ok {
		return fmt.Errorf("field taskId in TaskCompletedSchemaJson: required")
	}
	type Plain TaskCompletedSchemaJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = TaskCompletedSchemaJson(plain)
	return nil
}

type TaskCreatedSchemaJson struct {
	// AgentConfigRef corresponds to the JSON schema field "agentConfigRef".
	AgentConfigRef *string `json:"agentConfigRef,omitempty" yaml:"agentConfigRef,omitempty" mapstructure:"agentConfigRef,omitempty"`

	// Immutable once created (INV-1).
	CanonicalPrompt string `json:"canonicalPrompt" yaml:"canonicalPrompt" mapstructure:"canonicalPrompt"`

	// Origin corresponds to the JSON schema field "origin".
	Origin TaskCreatedSchemaJsonOrigin `json:"origin" yaml:"origin" mapstructure:"origin"`

	// ParentTaskId corresponds to the JSON schema field "parentTaskId".
	ParentTaskId *string `json:"parentTaskId,omitempty" yaml:"parentTaskId,omitempty" mapstructure:"parentTaskId,omitempty"`

	// Risk corresponds to the JSON schema field "risk".
	Risk TaskCreatedSchemaJsonRisk `json:"risk" yaml:"risk" mapstructure:"risk"`

	// TaskId corresponds to the JSON schema field "taskId".
	TaskId string `json:"taskId" yaml:"taskId" mapstructure:"taskId"`

	// WorkspaceId corresponds to the JSON schema field "workspaceId".
	WorkspaceId string `json:"workspaceId" yaml:"workspaceId" mapstructure:"workspaceId"`
}

type TaskCreatedSchemaJsonOrigin string

const TaskCreatedSchemaJsonOriginApi TaskCreatedSchemaJsonOrigin = "api"
const TaskCreatedSchemaJsonOriginChannel TaskCreatedSchemaJsonOrigin = "channel"
const TaskCreatedSchemaJsonOriginCron TaskCreatedSchemaJsonOrigin = "cron"
const TaskCreatedSchemaJsonOriginHook TaskCreatedSchemaJsonOrigin = "hook"
const TaskCreatedSchemaJsonOriginManual TaskCreatedSchemaJsonOrigin = "manual"

var enumValues_TaskCreatedSchemaJsonOrigin = []interface{}{
	"manual",
	"cron",
	"hook",
	"api",
	"channel",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskCreatedSchemaJsonOrigin) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskCreatedSchemaJsonOrigin {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskCreatedSchemaJsonOrigin, v)
	}
	*j = TaskCreatedSchemaJsonOrigin(v)
	return nil
}

type TaskCreatedSchemaJsonRisk string

const TaskCreatedSchemaJsonRiskHigh TaskCreatedSchemaJsonRisk = "high"
const TaskCreatedSchemaJsonRiskLow TaskCreatedSchemaJsonRisk = "low"
const TaskCreatedSchemaJsonRiskMedium TaskCreatedSchemaJsonRisk = "medium"

var enumValues_TaskCreatedSchemaJsonRisk = []interface{}{
	"low",
	"medium",
	"high",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskCreatedSchemaJsonRisk) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskCreatedSchemaJsonRisk {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskCreatedSchemaJsonRisk, v)
	}
	*j = TaskCreatedSchemaJsonRisk(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskCreatedSchemaJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["canonicalPrompt"]; raw != nil && !ok {
		return fmt.Errorf("field canonicalPrompt in TaskCreatedSchemaJson: required")
	}
	if _, ok := raw["origin"]; raw != nil && !ok {
		return fmt.Errorf("field origin in TaskCreatedSchemaJson: required")
	}
	if _, ok := raw["risk"]; raw != nil && !ok {
		return fmt.Errorf("field risk in TaskCreatedSchemaJson: required")
	}
	if _, ok := raw["taskId"]; raw != nil && !ok {
		return fmt.Errorf("field taskId in TaskCreatedSchemaJson: required")
	}
	if _, ok := raw["workspaceId"]; raw != nil && !ok {
		return fmt.Errorf("field workspaceId in TaskCreatedSchemaJson: required")
	}
	type Plain TaskCreatedSchemaJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = TaskCreatedSchemaJson(plain)
	return nil
}

type TaskFailedSchemaJson struct {
	// True if a saga compensation was emitted instead of rollback.
	Compensating *bool `json:"compensating,omitempty" yaml:"compensating,omitempty" mapstructure:"compensating,omitempty"`

	// Typed error class (fail-fast, spec P6).
	ErrorCode string `json:"errorCode" yaml:"errorCode" mapstructure:"errorCode"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message" yaml:"message" mapstructure:"message"`

	// TaskId corresponds to the JSON schema field "taskId".
	TaskId string `json:"taskId" yaml:"taskId" mapstructure:"taskId"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskFailedSchemaJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["errorCode"]; raw != nil && !ok {
		return fmt.Errorf("field errorCode in TaskFailedSchemaJson: required")
	}
	if _, ok := raw["message"]; raw != nil && !ok {
		return fmt.Errorf("field message in TaskFailedSchemaJson: required")
	}
	if _, ok := raw["taskId"]; raw != nil && !ok {
		return fmt.Errorf("field taskId in TaskFailedSchemaJson: required")
	}
	type Plain TaskFailedSchemaJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = TaskFailedSchemaJson(plain)
	return nil
}

type TaskPlannedSchemaJson struct {
	// Ordered plan steps the agent intends to execute.
	Plan []TaskPlannedSchemaJsonPlanElem `json:"plan" yaml:"plan" mapstructure:"plan"`

	// TaskId corresponds to the JSON schema field "taskId".
	TaskId string `json:"taskId" yaml:"taskId" mapstructure:"taskId"`
}

type TaskPlannedSchemaJsonPlanElem struct {
	// StepId corresponds to the JSON schema field "stepId".
	StepId string `json:"stepId" yaml:"stepId" mapstructure:"stepId"`

	// Summary corresponds to the JSON schema field "summary".
	Summary string `json:"summary" yaml:"summary" mapstructure:"summary"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskPlannedSchemaJsonPlanElem) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["stepId"]; raw != nil && !ok {
		return fmt.Errorf("field stepId in TaskPlannedSchemaJsonPlanElem: required")
	}
	if _, ok := raw["summary"]; raw != nil && !ok {
		return fmt.Errorf("field summary in TaskPlannedSchemaJsonPlanElem: required")
	}
	type Plain TaskPlannedSchemaJsonPlanElem
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = TaskPlannedSchemaJsonPlanElem(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskPlannedSchemaJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["plan"]; raw != nil && !ok {
		return fmt.Errorf("field plan in TaskPlannedSchemaJson: required")
	}
	if _, ok := raw["taskId"]; raw != nil && !ok {
		return fmt.Errorf("field taskId in TaskPlannedSchemaJson: required")
	}
	type Plain TaskPlannedSchemaJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = TaskPlannedSchemaJson(plain)
	return nil
}

type TurnCompletedSchemaJson struct {
	// Metrics corresponds to the JSON schema field "metrics".
	Metrics *TurnCompletedSchemaJsonMetrics `json:"metrics,omitempty" yaml:"metrics,omitempty" mapstructure:"metrics,omitempty"`

	// Outcome corresponds to the JSON schema field "outcome".
	Outcome TurnCompletedSchemaJsonOutcome `json:"outcome" yaml:"outcome" mapstructure:"outcome"`

	// TaskId corresponds to the JSON schema field "taskId".
	TaskId string `json:"taskId" yaml:"taskId" mapstructure:"taskId"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId" yaml:"turnId" mapstructure:"turnId"`
}

type TurnCompletedSchemaJsonMetrics struct {
	// CostUsd corresponds to the JSON schema field "costUsd".
	CostUsd *float64 `json:"costUsd,omitempty" yaml:"costUsd,omitempty" mapstructure:"costUsd,omitempty"`

	// Tokens corresponds to the JSON schema field "tokens".
	Tokens *int `json:"tokens,omitempty" yaml:"tokens,omitempty" mapstructure:"tokens,omitempty"`

	// WallClockMs corresponds to the JSON schema field "wallClockMs".
	WallClockMs *int `json:"wallClockMs,omitempty" yaml:"wallClockMs,omitempty" mapstructure:"wallClockMs,omitempty"`
}

type TurnCompletedSchemaJsonOutcome string

const TurnCompletedSchemaJsonOutcomeError TurnCompletedSchemaJsonOutcome = "error"
const TurnCompletedSchemaJsonOutcomeNeedsApproval TurnCompletedSchemaJsonOutcome = "needs_approval"
const TurnCompletedSchemaJsonOutcomeOk TurnCompletedSchemaJsonOutcome = "ok"

var enumValues_TurnCompletedSchemaJsonOutcome = []interface{}{
	"ok",
	"needs_approval",
	"error",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TurnCompletedSchemaJsonOutcome) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TurnCompletedSchemaJsonOutcome {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TurnCompletedSchemaJsonOutcome, v)
	}
	*j = TurnCompletedSchemaJsonOutcome(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TurnCompletedSchemaJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["outcome"]; raw != nil && !ok {
		return fmt.Errorf("field outcome in TurnCompletedSchemaJson: required")
	}
	if _, ok := raw["taskId"]; raw != nil && !ok {
		return fmt.Errorf("field taskId in TurnCompletedSchemaJson: required")
	}
	if _, ok := raw["turnId"]; raw != nil && !ok {
		return fmt.Errorf("field turnId in TurnCompletedSchemaJson: required")
	}
	type Plain TurnCompletedSchemaJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = TurnCompletedSchemaJson(plain)
	return nil
}

type TurnStartedSchemaJson struct {
	// InputSummary corresponds to the JSON schema field "inputSummary".
	InputSummary *string `json:"inputSummary,omitempty" yaml:"inputSummary,omitempty" mapstructure:"inputSummary,omitempty"`

	// TaskId corresponds to the JSON schema field "taskId".
	TaskId string `json:"taskId" yaml:"taskId" mapstructure:"taskId"`

	// TurnId corresponds to the JSON schema field "turnId".
	TurnId string `json:"turnId" yaml:"turnId" mapstructure:"turnId"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TurnStartedSchemaJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["taskId"]; raw != nil && !ok {
		return fmt.Errorf("field taskId in TurnStartedSchemaJson: required")
	}
	if _, ok := raw["turnId"]; raw != nil && !ok {
		return fmt.Errorf("field turnId in TurnStartedSchemaJson: required")
	}
	type Plain TurnStartedSchemaJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = TurnStartedSchemaJson(plain)
	return nil
}

type WorkspaceCreatedSchemaJson struct {
	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// WorkspaceId corresponds to the JSON schema field "workspaceId".
	WorkspaceId string `json:"workspaceId" yaml:"workspaceId" mapstructure:"workspaceId"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WorkspaceCreatedSchemaJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in WorkspaceCreatedSchemaJson: required")
	}
	if _, ok := raw["workspaceId"]; raw != nil && !ok {
		return fmt.Errorf("field workspaceId in WorkspaceCreatedSchemaJson: required")
	}
	type Plain WorkspaceCreatedSchemaJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = WorkspaceCreatedSchemaJson(plain)
	return nil
}
