export function buildDefaultDesignSystemMarkdown(): string {
  return [
    "---",
    "name: Workspace Design System",
    "description: Shared visual source of truth for CoWork OS frontend work in this workspace.",
    "colors:",
    "  background: \"#0f1115\"",
    "  surface: \"#171a21\"",
    "  surfaceElevated: \"#20242e\"",
    "  text: \"#f5f7fb\"",
    "  textMuted: \"#9aa3b2\"",
    "  primary: \"#22d3ee\"",
    "  primaryHover: \"#67e8f9\"",
    "  success: \"#34d399\"",
    "  warning: \"#fbbf24\"",
    "  danger: \"#f87171\"",
    "typography:",
    "  fontFamily:",
    "    ui: \"-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', sans-serif\"",
    "    mono: \"'SF Mono', 'Fira Code', Consolas, monospace\"",
    "  scale:",
    "    body: \"14px\"",
    "    small: \"12px\"",
    "    heading: \"20px\"",
    "spacing:",
    "  xs: \"4px\"",
    "  sm: \"8px\"",
    "  md: \"12px\"",
    "  lg: \"16px\"",
    "  xl: \"24px\"",
    "radii:",
    "  sm: \"8px\"",
    "  md: \"10px\"",
    "  lg: \"14px\"",
    "components:",
    "  button:",
    "    radius: \"{radii.sm}\"",
    "    background: \"{colors.primary}\"",
    "    text: \"#001014\"",
    "  panel:",
    "    radius: \"{radii.md}\"",
    "    background: \"{colors.surface}\"",
    "    border: \"rgba(255, 255, 255, 0.12)\"",
    "---",
    "",
    "# Design System",
    "",
    "## Purpose",
    "Use this file as the workspace source of truth for frontend and UI work. Agents should consult it before changing visual hierarchy, colors, typography, spacing, component treatments, or motion.",
    "",
    "## Principles",
    "- Prefer calm, dense, operator-friendly interfaces over marketing-style layouts for product surfaces.",
    "- Preserve these tokens unless the user explicitly asks for a redesign.",
    "- When introducing new UI, map values back to the closest token instead of inventing one-off colors or radii.",
    "- If a requested visual direction conflicts with this file, call out the conflict and ask only when the tradeoff is material.",
    "",
    "## Component Guidance",
    "- Buttons use the primary token for clear actions and neutral surfaces for secondary actions.",
    "- Panels should feel integrated with the workspace, not like nested decorative cards.",
    "- Text hierarchy should be clear at a glance: labels, values, controls, and status should not compete.",
    "",
    "## Motion",
    "- Use restrained motion for orientation, state changes, and progressive disclosure.",
    "- Avoid decorative motion that makes repeated workflows slower.",
    "",
  ].join("\n");
}
