/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dispatch a command (the only write path into the kernel)
         * @description All state changes go through commands. The kernel validates invariants in a single Postgres transaction and appends events. Returns the committed events, or a typed DomainError (fail-fast, no silent nulls).
         */
        post: operations["dispatchCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/query/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read-only projection query (never returns mutable domain objects) */
        get: operations["runQuery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket event stream (Upgrade required; see description)
         * @description WebSocket endpoint. Client connects with Bearer token, sends a filter (workspaceIds, types) and a resume cursor. Server pushes CommittedEvent frames, fan-out across gateway replicas via PubSub. On reconnect the client resumes from its persisted cursor (idempotent, at-least-once). Token refresh: the short-lived JWT may expire mid-connection; the client sends a `reauth` control frame with a fresh token before expiry, and the server closes the socket (4401) if no valid token is presented in time, prompting the client to reconnect-and-resume. Not a plain HTTP GET; expressed here for documentation only.
         */
        get: operations["subscribeStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Capability + permission gate for a guarded action
         * @description Runs the deterministic decision pipeline (spec 11.2): verify the presented capability (signature, expiry, revocation), then evaluate the permission rule matrix. allow proceeds; ask emits an ApprovalRequested event on the task; deny returns a typed capability/permission error.
         */
        post: operations["authorizeAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** External programmatic API - create a durable run (maps to Task/AgentTeamRun) */
        post: operations["createManagedSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getManagedSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SSE event stream for a managed session */
        get: operations["streamManagedSessionEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelManagedSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Opaque resume position; encodes the per-shard monotonic visible global_seq. */
        Cursor: string;
        Command: {
            /** @description Command name, e.g. CreateTask, StartTurn, ResolveApproval. */
            type: string;
            /** @description Command-specific fields (validated against the command schema). */
            payload: {
                [key: string]: unknown;
            };
            /** @description Dedup key for safe client retries. */
            idempotencyKey?: string;
            /**
             * Format: int64
             * @description Optimistic concurrency guard; reject if the stream advanced.
             */
            expectedStreamSeq?: number;
        };
        /** @description Event envelope as appended to event_log. The payload conforms to the JSON Schema named by `type` under contracts/events/. */
        CommittedEvent: {
            /** Format: int64 */
            globalSeq: number;
            tenantId: string;
            /** @description Aggregate instance, e.g. task:<id> */
            streamId: string;
            /** Format: int64 */
            streamSeq: number;
            type: string;
            schemaVer: number;
            payload: {
                [key: string]: unknown;
            };
            actor: string;
            correlationId?: string;
            causationId?: string;
            /** Format: date-time */
            occurredAt: string;
        };
        /** @description Typed, fail-fast error. One handling site per error class. */
        DomainError: {
            /** @description Stable machine code, e.g. concurrency_conflict, invariant_violated, capability_denied. */
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
            correlationId?: string;
        };
        ReadModelPage: {
            items: {
                [key: string]: unknown;
            }[];
            nextCursor?: components["schemas"]["Cursor"];
        };
        Budget: {
            maxTokens?: number;
            maxCostUsd?: number;
            maxWallClockSec?: number;
        };
        ActionRequest: {
            taskId: string;
            /** @description Resource class, e.g. fs.read, fs.write, net, shell, data_export, tool:<name>. */
            resource: string;
            /** @enum {string} */
            risk?: "low" | "medium" | "high";
            inScope?: boolean;
            outsideScope?: boolean;
            domainAllowListed?: boolean;
            /** @description Server-signed capability envelope; verified at use-time. */
            capabilityToken?: string;
            context?: {
                [key: string]: unknown;
            };
        };
        ActionResult: {
            /** @enum {string} */
            decision: "allow" | "ask" | "deny";
            /** @description Matched permission rule id (audit). */
            ruleId: string;
            events?: components["schemas"]["CommittedEvent"][];
        };
        ManagedSession: {
            id: string;
            taskId?: string;
            /** @enum {string} */
            status: "pending" | "running" | "awaiting_approval" | "completed" | "failed" | "cancelled";
            result?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dispatchCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Command"];
            };
        };
        responses: {
            /** @description Command accepted; events committed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        events: components["schemas"]["CommittedEvent"][];
                    };
                };
            };
            /** @description AuthZ / capability denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainError"];
                };
            };
            /** @description Optimistic concurrency conflict; reload and retry. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainError"];
                };
            };
            /** @description Domain invariant violated. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainError"];
                };
            };
        };
    };
    runQuery: {
        parameters: {
            query?: {
                cursor?: components["schemas"]["Cursor"];
                limit?: number;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Read model page, filtered by identity/tenant. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadModelPage"];
                };
            };
            /** @description Unknown query name. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainError"];
                };
            };
        };
    };
    subscribeStream: {
        parameters: {
            query?: {
                cursor?: components["schemas"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching Protocols (WebSocket). */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authorizeAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Decision (allow or ask). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResult"];
                };
            };
            /** @description Capability or permission denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainError"];
                };
            };
        };
    };
    createManagedSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    prompt: string;
                    workspaceId?: string;
                    budget?: components["schemas"]["Budget"];
                };
            };
        };
        responses: {
            /** @description Session created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedSession"];
                };
            };
        };
    };
    getManagedSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session state (read-model projection). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedSession"];
                };
            };
        };
    };
    streamManagedSessionEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream of CommittedEvent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    cancelManagedSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancel command accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        events?: components["schemas"]["CommittedEvent"][];
                    };
                };
            };
        };
    };
}
